trigger: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily Next Major build
  branches:
    include:
    - master
  always: true

pool:
  name: default

variables:
- group: BuildVariables

jobs:
- job: Build
  variables:
    build.clean: all
    platform: x64
    version: "nextmajor"
    appBuild: $[counter(variables['appVersion'],0)]
    appRevision: 0
    createRuntimePackages: True
    skipComponentGovernanceDetection: True

  steps:
  - task: PowerShell@2
    displayName: 'Install BcContainerHelper'
    inputs:
      targetType: filePath
      filePath: 'scripts\Install-BcContainerHelper.ps1'
      failOnStderr: true

  - task: PowerShell@2
    displayName: 'Run Pipeline'
    env:
      InsiderSasToken: '$(InsiderSasToken)'
      LicenseFile: '$(LicenseFile)'
      CodeSignCertPfxFile: '$(CodeSignCertPfxFile)'
      CodeSignCertPfxPassword: '$(CodeSignCertPfxPassword)'
    inputs:
      targetType: filePath
      filePath: 'scripts\DevOps-Pipeline.ps1'
      arguments: '-version "$(version)"'
      failOnStderr: true

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: and(succeeded(),eq(variables['TestResultsAvailable'],'True'))
    inputs:
      testResultsFormat: XUnit
      testResultsFiles: TestResults.xml
      failTaskOnFailedTests: true
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: output

  - task: PowerShell@2
    displayName: 'Cleanup'
    inputs:
      targetType: inline
      script: 'Flush-ContainerHelperCache -KeepDays 7'
      failOnStderr: false
